baseURL = 'https://archive.bersp.xyz'
languageCode = 'en-us'
title = 'Archive'

[markup]
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
